# Generated by Django 5.2 on 2025-04-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='titles', to='roles.permission'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='organizations.title'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('organization', 'email')},
        ),
    ]
