# Generated by Django 5.1.7 on 2025-03-31 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('project_status', 'Project Status Report'), ('team_productivity', 'Team Productivity Report'), ('task_completion', 'Task Completion Report'), ('time_tracking', 'Time Tracking Report'), ('overdue_tasks', 'Overdue Tasks Report')], max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configurations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
