# Generated by Django 5.1.7 on 2025-03-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_title'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='budget_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('admin', 'Administrative'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('planning', 'Planning'), ('research', 'Research'), ('sales', 'Sales'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='client_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='time_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team'), ('private', 'Private'), ('public', 'Public')], default='team', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TaskApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers_through', to='tasks.task')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approving_tasks_through', to='organizations.teammember')),
            ],
            options={
                'unique_together': {('task', 'team_member')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees_through', to='tasks.task')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_through', to='organizations.teammember')),
            ],
            options={
                'unique_together': {('task', 'team_member')},
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_task1', to='tasks.task')),
                ('task2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_task2', to='tasks.task')),
            ],
            options={
                'unique_together': {('task1', 'task2')},
            },
        ),
        migrations.CreateModel(
            name='TaskPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks_through', to='tasks.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_through', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'prerequisite_task')},
            },
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers_through', to='tasks.task')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_tasks_through', to='organizations.teammember')),
            ],
            options={
                'unique_together': {('task', 'team_member')},
            },
        ),
    ]
