# Generated by Django 5.2 on 2025-04-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('create_tasks', 'Create Tasks'), ('view_tasks', 'View Tasks'), ('assign_tasks', 'Assign Tasks'), ('update_tasks', 'Update Tasks'), ('delete_tasks', 'Delete Tasks'), ('approve_tasks', 'Approve Tasks'), ('reject_tasks', 'Reject Tasks'), ('comment', 'Comment'), ('view_reports', 'View Reports'), ('manage_users', 'Manage Users'), ('manage_roles', 'Manage Roles')], max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
                ('permissions', models.ManyToManyField(related_name='roles', to='roles.permission')),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
